[package]
name = "surreal-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal_type_generator = { path = "../surreal_type_generator", version = "0.1.0" }
anyhow = "1.0.66"
clap = { version = "4.5.9", features = ["derive"] }
